[workspace]

members = ["per_set", "playground", "queries", "queries_check", "sparse_vec", "test_utils"]
resolver = "2"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
missing_errors_doc = "allow"
too_many_lines = "allow"

# bugs around Future<_> + Send
manual_async_fn = "allow" 
