[package]
name = "cache_analyzer_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tracer_types = { path = "../tracer_types" }
rocket = { version = "0.5", features = ["json"] }
serde = "1"
per_set = { path = "../per_set" }
rocket_cors = "0.6.0"

[lints]
workspace = true
