[package]
name = "sparse_vec"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = { version = "1", features = ["union", "const_generics"] }

[dev-dependencies]
proptest = "1"
test_utils = { path = "../test_utils" }


[lints]
workspace = true
